title: Lucas Rocha
tagline: Lucas Rocha
description: Lucas Rocha's personal website.
canonical: http://lucasr.org
lang: en_GB

author:
  name: Lucas Rocha
  bio: >
      Building UI frameworks and tools at Facebook in London.
      Formerly at Mozilla, GNOME, litl, and Nokia.
      Brazilian, husband, dad.
  email: lucasr@lucasr.org
  twitter: lucasratmundo
  linkedin: lucasr
  instagram: lucasratmundo
  github: lucasr

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
